-- USE PHP MYADMIN TO CREATE PROCEDURES IN database atropostest

-- getAddress parameter (user varchar255)
SELECT DISTINCT ADDRESS.HouseNum, ADDRESS.Street, ADDRESS.City, ADDRESS.Province
FROM ADDRESS, USER, CUSTOMER
WHERE ADDRESS.HouseNum = CUSTOMER.HouseNum 
AND CUSTOMER.Username = user

-- getBottoms
SELECT PRODUCTS.*, PANTS.TYPE
FROM PANTS, PRODUCTS
WHERE PANTS.PRODID = PRODUCTS.PRODID

-- getCart parameter (user varchar255)
-- SELECT PRODUCTS.Type, PRODUCTS.Color, PRODUCTS.Price, PRODUCTS.Size, PRODUCTS.ProdID
-- FROM SHOPPINGCART, PRODUCTS
-- WHERE PRODUCTS.ProdID = SHOPPINGCART.ProdID
-- AND SHOPPINGCART.Username =  user

-- getJackets
SELECT PRODUCTS.*, JACKETS.TYPE
FROM JACKETS, PRODUCTS
WHERE JACKETS.PRODID = PRODUCTS.PRODID

-- getPants
SELECT PRODUCTS.*, PANTS.TYPE
FROM PANTS, PRODUCTS
WHERE PANTS.PRODID = PRODUCTS.PRODID
AND PANTS.TYPE NOT LIKE '%shorts'

-- getShirts
-- SELECT PRODUCTS.*, SHIRTS.TYPE
-- FROM SHIRTS, PRODUCTS
-- WHERE SHIRTS.PRODID = PRODUCTS.PRODID

-- getShorts
-- SELECT PRODUCTS.*, PANTS.TYPE
-- FROM PANTS, PRODUCTS
-- WHERE PANTS.PRODID = PRODUCTS.PRODID
-- AND PANTS.TYPE LIKE '%shorts'

-- getTops
SELECT PRODUCTS.*, JACKETS.TYPE
FROM JACKETS, PRODUCTS
WHERE JACKETS.PRODID = PRODUCTS.PRODID
UNION
SELECT PRODUCTS.*, SHIRTS.TYPE
FROM SHIRTS, PRODUCTS
WHERE SHIRTS.PRODID = PRODUCTS.PRODID

-- getWish parameter (user varchar255)
SELECT PRODUCTS.Type, PRODUCTS.Color, PRODUCTS.Price, PRODUCTS.Size, PRODUCTS.ProdID
FROM WISHLIST, PRODUCTS
WHERE PRODUCTS.ProdID = WISHLIST.ProdID
AND WISHLIST.Username =  user